language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: LiIn+EKMvCmLq2ylwp26kaTLrkgGy0iBp5UAaQNW1BmDlbxtRclRUfercyA/e51TMS7ZGbSGCyTC4C3n+Kvn4CouFvm1g52ynUjKDs0y5U6bE0nmbzFZrZAEaR3Ai7z9AvGauW54XihTgmylpcC1aRUQ1Gqu3Ax7epNNToobJL/g71sLQfCZOwvYkIOs498+8eNYeS8afJrSYmbQDoq9E5Cu4NGR/vJZWevkjMaJCh320g3hQAd4XNkKp0tuvR6or4evgTpFeE1sZhvqYLLQiTHMki47A12VDfJyl32R7Gu7przibbpca8YjfCawXd490lRLkj93Gwkl4OqN37+b/JWTweLtJwCMzi39AOrrYvqevQ/I1fPAIE3UrT6GJ4Sa9sto70DXWpgCKn5iIhg1ZKFB18gjENZHoJZZYLa9Hl7igi9QrCv6w1Jcrb1IQi7YySXp5etwGsmltVmDtrV81+QRMokwGVOgY5tNYfBckJbXsIBP3+Mfhja8iIktLUXvyvvpUCPgpq7B68vlPSarKp0MNiDZBHGE+HJEDyQxZdY8tXEB7mJsqMGTYAMv2E5n57zj4ersSO1kImAFG71P6tblNLZBNUrzeePtjE8Xzuu1yaQro+cQf9nabZLuj9A27vGRbmm3n6RWRgL2FY4JWGVzMPKwvMb9mKoOBVINjbI=
  file:
    - "hast-util-to-nlcst.js"
    - "hast-util-to-nlcst.min.js"
  on:
    tags: true
